#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/major/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/major/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/major/trial/network/x86_64/.libs/libnrnmech.so" "$@"
